add kite

diff --git a/scripts/vclip b/scripts/vclip
--- a/scripts/vclip
+++ b/scripts/vclip
@@ -5,30 +5,15 @@ if ! [ -x "$(command -v $EDITOR)" ]; then
   exit 1
 fi
 
-if [ "Darwin" = $(uname -s) ]; then
-    if ! [ -x "$(command -v pbcopy)" ]; then
-      echo 'Error: pbcopy is not available.' >&2
-      exit 1
-    fi
+if ! [ -x "$(command -v xsel)" ]; then
+  echo 'Error: xsel is not available.' >&2
+  exit 1
+fi
 
-    TMP=$(mktemp -t vimclip)
-    $EDITOR $TMP
-    if [ -s $TMP ]; then
-        pbcopy < $TMP
-    else
-        rm $TMP
-    fi
+TMP=$(mktemp -p /tmp -t vimclip.XXXXXXXX.md)
+$EDITOR $TMP
+if [ -s $TMP ]; then
+  xsel -i -b < $TMP
 else
-    if ! [ -x "$(command -v xsel)" ]; then
-      echo 'Error: xsel is not available.' >&2
-      exit 1
-    fi
-
-    TMP=$(mktemp -p /tmp -t vimclip.XXXXXXXX)
-    $EDITOR $TMP
-    if [ -s $TMP ]; then
-        xsel -i -b < $TMP
-    else
-        rm $TMP
-    fi
+  rm $TMP
 fi
